### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by jasonfghx** [Beramos/Data-on-ion-exchange-membrane-fouling-by-humic-acid-during-electrodialysis#1]
https://zenodo.org/deposit/3551928#

excuse me, do you mind to share the data for me?
thx

**Comment by Beramos** [comment]
Hey
We are still waiting for the paper to get accepted. After which I'll make
the data public.
Kind regards,
Bram

Op zo 15 mrt. 2020 08:34 schreef jasonfghx <notifications@github.com>:

**Comment by jasonfghx** [comment]
thanks for replying my question so quickly.
My company is a manufacturer from Taiwan of electrodialysis equipment.
you can refer to the image as the website "http://www.recyclesources.com.tw/upload/cht/user/service/33/249_service_sell_2.jpg"
I am curious about what kind of data you have and look forward for further connection.
Kind regards,

**Comment by Beramos** [comment]
The data consists of different time-series of the resistance increase of
the stack under different operational conditions during electrodialysis
reversal. I keep you up to date whenever we make the dataset publicly
available.
Kind regards,
Bram

Op zo 15 mrt. 2020 om 09:51 schreef jasonfghx <notifications@github.com>:

**Comment by Beramos** [comment]
The article is available [here](https://doi.org/10.1016/j.dib.2020.105763)

The data is available [here](https://zenodo.org/record/3551928#.XtDA-_xS8UE)
